defaults:
  - serialization: kv_pairs
  - retrieval: top_k
  - prompt: raw_stuffing
  - override hydra/job_logging: custom
  - _self_

experiment_name: "default_benchmark"
output_dir: "./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}"
